---
# target specific nodes
# ansible-playbook site.yml

# runs on all servers
- hosts: all
  become: true
  pre_tasks:
    # `pre_tasks:` can be used with roles when we want to mandate some things to run before others
    - name: update repo cache (CentOS)
      tags: always
      dnf:
        update_cache: true
      changed_when: false
      when: ansible_distribution = "CentOS"

    - name: update repo cache (Ubuntu)
      tags: always
      apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

# runs only on web_servers defined in the `inventory` file
- hosts: web_servers
  become: true
  roles:
    - web_servers

# runs only on db_servers defined in the `inventory` file
- hosts: db_servers
  become: true
  roles:
    - db_servers

# runs only on file_servers defined in the `inventory` file
- hosts: file_servers
  become: true
  roles:
    - file_servers
