---
- name: Import Keypair
  ec2_key:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    state: "{{ key_state }}"
    name: "ansible-ssh-keypair"
    key_material: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFXD/2yOLiokF6Um7M+Z8kcIA67Col5fSK/vqfVP2W3C ec2@sydrawat-aws-dev"
