services:
  app:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    restart: always
  redis:
    image: redis:latest
