---
# ansible-playbook --ask-become-pass remove_apache.yml
- hosts: all
  become: true
  tasks:
    # - name: "update repository index"
    #   apt:
    #     update_cache: true

    - name: "remove the apache2 package"
      apt:
        name: apache2
        state: absent

    - name: "remove php support for apache"
      apt:
        name: libapache2-mod-php
        state: absent
