---
# target specific nodes
# ansible-playbook --ask-become-pass site.yml

# runs on all servers
- hosts: all
  become: true
  tasks:
    # `pre_tasks:` can be used with roles when we want to mandate some things to run before others
    - name: install updates (CentOS)
      tags: always
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution = "CentOS"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip # download link address
        dest: /usr/local/bin # downloads binary here
        remote_src: true # notify ansible that this package is from the internet and not a package manager
        mode: 0755
        owner: root
        group: root

# runs only on web_servers defined in the `inventory` file
- hosts: web_servers
  become: true
  tasks:
    - name: "install the apache2 and php package for Ubuntu"
      tags: apache,apache2, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: "install the apache and php package for CentOS"
      tags: apache,centos,https
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: start httpd (CentOS)
      tags: apache,centos,httpd
      service: # module to start/stop/restart/enable a service
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution = "CentOS"

    - name: change e-mail address for admin
      tags: apache,centos,httpd
      lineinfile: # module to be used to change a line in a file
        path: /etc/httpd/conf/httpd.conf # path to file which is to be changed
        regexp: "^ServerAdmin" # for line beginning with "serverAdmin"
        line: ServerAdmin somebody@somewhere.net # replace it with this line
      when: ansible_distribution == "CentOS"
      registered: httpd # capture the state in a variable and check it against httpd.changed

    - name: restart httpd (CentOS)
      tags: apache,centos,httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

# runs only on db_servers defined in the `inventory` file
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      tags: centos,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

# runs only on file_servers defined in the `inventory` file
- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
